language: php

sudo: false

php:
  - 7.0
  - hhvm

env:
  global:
    - GIT_NAME:  "'Marco Pivetta'"
    - GIT_EMAIL: ocramius@gmail.com
    - GH_REF:    github.com/Ocramius/ProxyManager
    - secure: HUDB66EnmKFx2A+E3HxvuX/7XSjgfNy8dnzcpG+K9mf/JM5JXZflK3xO3J3LCgSQG6Ptwr2yy//7vX+PdJMdSRTmP+d/dy6v8yLRP+GvYZXLIbuKg7dQjLerOxJcy9JhU2eAEBevc002PwFqLalfhCyWLvLiCof8++E2uGbvTSU=

before_script:
  - sh .travis.install.sh

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml --group=Coverage
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --exclude-group=Performance,Coverage
  - php -n ./vendor/bin/phpunit --group=Performance
  # - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

matrix:
  allow_failures:
    - php: hhvm

after_script:
  - sh .travis.coverage.sh
  - ./vendor/bin/couscous travis-auto-deploy --php-version=7.0
