language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  global:
    - GIT_NAME:  "'Marco Pivetta'"
    - GIT_EMAIL: ocramius@gmail.com
    - GH_REF:    github.com/Ocramius/ProxyManager
    - secure:    "KEY"

before_script:
  - sh .travis.install.sh
  - composer global require couscous/couscous

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml --group=Coverage
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --strict --exclude-group=Performance,Coverage
  - php -n ./vendor/bin/phpunit --group=Performance
#  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

after_script:
  - sh .travis.coverage.sh
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml

after_success:
  - couscous travis-auto-deploy --php-version=5.5

